// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwsb-OKv_IgzijT1UE1bTfNfOpXgwtVFA',
    appId: '1:295759948036:web:1e795aa6b859769fd4c851',
    messagingSenderId: '295759948036',
    projectId: 'mova-f7135',
    authDomain: 'mova-f7135.firebaseapp.com',
    storageBucket: 'mova-f7135.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq8FZ_StndQ2KgmVVVWak-BrAEEtktXG4',
    appId: '1:295759948036:android:4a090902c395cfdbd4c851',
    messagingSenderId: '295759948036',
    projectId: 'mova-f7135',
    storageBucket: 'mova-f7135.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAug467iJ9Khtcyc6fDxPBvUuCOuj__mi0',
    appId: '1:295759948036:ios:74407d66d69ddbbcd4c851',
    messagingSenderId: '295759948036',
    projectId: 'mova-f7135',
    storageBucket: 'mova-f7135.appspot.com',
    iosBundleId: 'com.example.movie1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwsb-OKv_IgzijT1UE1bTfNfOpXgwtVFA',
    appId: '1:295759948036:web:f87ad85d4e0db815d4c851',
    messagingSenderId: '295759948036',
    projectId: 'mova-f7135',
    authDomain: 'mova-f7135.firebaseapp.com',
    storageBucket: 'mova-f7135.appspot.com',
  );
}
